# Generated by Django 4.2.11 on 2025-01-02 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloomer', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.PositiveIntegerField(default=0)),
                ('tuesday', models.PositiveIntegerField(default=0)),
                ('wednesday', models.PositiveIntegerField(default=0)),
                ('thursday', models.PositiveIntegerField(default=0)),
                ('friday', models.PositiveIntegerField(default=0)),
                ('saturday', models.PositiveIntegerField(default=0)),
                ('sunday', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
